# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Quality Clouds Scan
        # You may pin to the exact commit or the version.
        # uses: qualityclouds/action-full-scan@b6139e614387852d33c82662289697c90b1c1fab
        uses: qualityclouds/action-full-scan@0.0.9
        with:
          # You need to provide a valid API key to connect the Quality Clouds ruleset against which your code will be checked
          token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRiYTQxYTc0ZDgwZWRkNzhjZmRkYWQ3ZTY4ZDZmYmFmMDg1N2E1NmVjYzBkM2NmMzAxMmQwNTZmMDk1NGE2OTdmYmI0YjA3YjdmOTNhYzg0In0.eyJhdWQiOiIyIiwianRpIjoiNGJhNDFhNzRkODBlZGQ3OGNmZGRhZDdlNjhkNmZiYWYwODU3YTU2ZWNjMGQzY2YzMDEyZDA1NmYwOTU0YTY5N2ZiYjRiMDdiN2Y5M2FjODQiLCJpYXQiOjE2MTQwNzk0NjAsIm5iZiI6MTYxNDA3OTQ2MCwiZXhwIjoxNjQ1NjE1NDYwLCJzdWIiOiI0MjMiLCJzY29wZXMiOlsibGl2ZS1jaGVjayJdfQ.cj0AYp7KcKJp18-1-raC_Mn_1wI-PcatzCrr5fc9WZVGBN_cVCIx2F20yJSBZfkfdeHjMpBxXq90z_DSohzz2XVx3xfI4Vv2MX2kxIK7jhMn2NqjySmTw-3YmoaG8Y1ey5PZctNnmu1xNx81e0AYNFKJlSj4-1C6dVL4WGiy339QQuR-KITEpjF2_z0NyYZlqiuQ1lLahuf4FiENNUGMXHYsv_mMsyaMFGD97v1CJqmNKtpGOUeqjYhbm81a6uxJmSvsaEDuoq8Uhe87gcpPuWTpmGIUcjR1opuq_wv4Iuddm30k66Niwi6CHzI87HTqYCWQey-FbFeu0kSDQYCqE-CTZM0MR1PcuRdfWXpBx3_6xJYL84DaGJl_F5gls_OqujLTQ4tUw1iSJKsjhJn8qMOOwktxaQRAt0-Wjxj1QvCOJ1iWTAnQTa0xVQO6HNdwNSkuB7w8Xhg17cUP6EXhVpdcmFYykj01vpIZCepYAuxaoFTxOvDWxd-EF6was2oXkWhRYKUxIrkzV8Ik-jjXyOx-3G2wrtEdsolJSZeOexyLEtmWwpcKwaezrDVhU0RebJiUSzBGSuClCZo1lbcHkDxsRihI1aF8gE1PIjjdmsSv5HbXhnH5PJNFO0zvmZ9OLFcQirw_2H6IKtD9fhBBFxzDBAAJugWO_vtgW9t-YBE'
          mode: cloud
          url_id: 315
