# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Quality Clouds Scan
        # You may pin to the exact commit or the version.
        # uses: qualityclouds/action-full-scan@b6139e614387852d33c82662289697c90b1c1fab
        uses: qualityclouds/action-full-scan@0.0.9
        with:
          # You need to provide a valid API key to connect the Quality Clouds ruleset against which your code will be checked
          token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRmMmJkOWIzYmE4OGM1NDEzM2ViNzM2MTNiODNjYzMzY2M0OWQxMDFlOTVlNzFkNGZjZGI4ODQ3OWNlOWUxMzZjMmVmNjcyYmY5N2NmNzMyIn0.eyJhdWQiOiIyIiwianRpIjoiNGYyYmQ5YjNiYTg4YzU0MTMzZWI3MzYxM2I4M2NjMzNjYzQ5ZDEwMWU5NWU3MWQ0ZmNkYjg4NDc5Y2U5ZTEzNmMyZWY2NzJiZjk3Y2Y3MzIiLCJpYXQiOjE2MTM0ODM4MDUsIm5iZiI6MTYxMzQ4MzgwNSwiZXhwIjoxNjQ1MDE5ODA1LCJzdWIiOiI0MjMiLCJzY29wZXMiOlsibGl2ZS1jaGVjayJdfQ.rrH3NL99DcjX3mp3K05TLmuLarVtgFj2vjiCxOsL94qPQ_5Yo3KpLr10kLtw9tihJ5VKlLBNbh9PjMKQ2rmL21jDaxgqWd7Tnpv5bH-IPJELsw2IyE7nixSmcGUmcV__pN0ecTmsUK0ayBZ-4Ot7U7G1DZVDcBbCCvZJsuduzMtu0NH7sPjVB9O78NYrEUuz3WfNBTF0WgRykx17heTzA1Fq4lVy6JJVrbKiPCNo5V5YQPBIbPfba69Eu5Kd1llVHwg94ecJ31XRfLoF9A6rvz5k0c9w3AI6i-ikoZaHib953h_ZyaA9HcPz-DLXKFQcJgo6s_5eu3ivy9DqP5Eaid-0sIbY4RVHdqJ60jYCtWkhY58UCoYPG00o77yPYM8hi_BStN0KduJxaqtJ-K4Ki8qmAxcfm0UCRALW4FUOKNAOj7SeMLEIvy09xXufopF5BX0xYsrFwxY0XOhW7bEm4rDU4PhSHhlhHuLPT6lJqQN97mnAnXnTopT0Qb8D2PMpsFHz7ARbZ0d0YCQjRdK5Lues9CEifpEQe4KFneyhVjMPeXbqan6j5oGXTF2yCOsGyMwqfvXW7HG8ojjeFO3Q2xZYE_VjWkRacO5SijpOE0mmxXF8Aifi6_7wA1Eubm9rSeIc-IRLfRLRhmLZkAM-h3meG4c0U4t1bqXfWLc1khQ'
          mode: cloud
          url_id: 315
