name: Quality Clouds SF BuildCheck Test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
      - '!testexcludebranch'
jobs:
  runbuildcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: qualityclouds/action-full-scan@v0.0.1
      with:
        token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRmMmJkOWIzYmE4OGM1NDEzM2ViNzM2MTNiODNjYzMzY2M0OWQxMDFlOTVlNzFkNGZjZGI4ODQ3OWNlOWUxMzZjMmVmNjcyYmY5N2NmNzMyIn0.eyJhdWQiOiIyIiwianRpIjoiNGYyYmQ5YjNiYTg4YzU0MTMzZWI3MzYxM2I4M2NjMzNjYzQ5ZDEwMWU5NWU3MWQ0ZmNkYjg4NDc5Y2U5ZTEzNmMyZWY2NzJiZjk3Y2Y3MzIiLCJpYXQiOjE2MTM0ODM4MDUsIm5iZiI6MTYxMzQ4MzgwNSwiZXhwIjoxNjQ1MDE5ODA1LCJzdWIiOiI0MjMiLCJzY29wZXMiOlsibGl2ZS1jaGVjayJdfQ.rrH3NL99DcjX3mp3K05TLmuLarVtgFj2vjiCxOsL94qPQ_5Yo3KpLr10kLtw9tihJ5VKlLBNbh9PjMKQ2rmL21jDaxgqWd7Tnpv5bH-IPJELsw2IyE7nixSmcGUmcV__pN0ecTmsUK0ayBZ-4Ot7U7G1DZVDcBbCCvZJsuduzMtu0NH7sPjVB9O78NYrEUuz3WfNBTF0WgRykx17heTzA1Fq4lVy6JJVrbKiPCNo5V5YQPBIbPfba69Eu5Kd1llVHwg94ecJ31XRfLoF9A6rvz5k0c9w3AI6i-ikoZaHib953h_ZyaA9HcPz-DLXKFQcJgo6s_5eu3ivy9DqP5Eaid-0sIbY4RVHdqJ60jYCtWkhY58UCoYPG00o77yPYM8hi_BStN0KduJxaqtJ-K4Ki8qmAxcfm0UCRALW4FUOKNAOj7SeMLEIvy09xXufopF5BX0xYsrFwxY0XOhW7bEm4rDU4PhSHhlhHuLPT6lJqQN97mnAnXnTopT0Qb8D2PMpsFHz7ARbZ0d0YCQjRdK5Lues9CEifpEQe4KFneyhVjMPeXbqan6j5oGXTF2yCOsGyMwqfvXW7HG8ojjeFO3Q2xZYE_VjWkRacO5SijpOE0mmxXF8Aifi6_7wA1Eubm9rSeIc-IRLfRLRhmLZkAM-h3meG4c0U4t1bqXfWLc1khQ'
